import {test} from 'node:test';
import assert from 'node:assert/strict';
import {guidedCourse as course} from '../src/content/guided-course';
import {freshGuided,changeGuided,completeGuided,keyFor,validAnswer,guidedStateSchema} from '@compass/studio-kit/guided';
import {guidedInsights} from '@compass/studio-kit/guided-rules';
test('all nine stages have unique ids, a review and a final reflection',()=>{assert.equal(new Set(course.map(s=>s.id)).size,9);for(const stage of course){assert.equal(new Set(stage.steps.map(s=>s.id)).size,stage.steps.length);assert.equal(stage.steps.at(-1)?.kind,'reflection');assert.ok(stage.steps.some(s=>s.kind==='review'));}});
test('completion cannot bypass unanswered steps; explicit unknown is retained',()=>{let state=freshGuided();assert.throws(()=>completeGuided(state,course[0]));for(const step of course[0].steps)state.answers[keyFor(course[0],step)]={status:'unknown',values:[]};state=completeGuided(state,course[0]);assert.ok(state.completed.includes(course[0].id));assert.equal(state.answers['setting-out/context'].status,'unknown');assert.equal(validAnswer({status:'known',values:[]}),false);});
test('editing flags dependent reports without deleting later answers',()=>{let state=freshGuided();state.completed=course.map(s=>s.id);state.answers['history/events']={status:'known',values:['یادگیری']};state=changeGuided(state,course,{status:'known',values:['شروع']});assert.equal(state.stale.length,9);assert.equal(state.answers['history/events'].values[0],'یادگیری');});
test('rules provide source ids and unknown wheel values never become zero',()=>{const state=freshGuided();state.answers['wheel/now']={status:'known',values:[],numbers:{'سلامت':2}};state.answers['wheel/future']={status:'known',values:[],numbers:{'سلامت':4,'خانه':5}};const insights=guidedInsights(course[3],state);assert.equal(insights.length,1);assert.deepEqual(insights[0].evidence,['now','future']);assert.ok(!insights[0].text.includes('خانه'));assert.throws(()=>guidedStateSchema.parse({...state,version:1}));});
