'use client';
import {useState} from 'react';
import type {GuidedAnswer,GuidedStep} from './guided';
export function Interaction({step,answer,onChange}:{step:GuidedStep;answer?:GuidedAnswer;onChange:(a:GuidedAnswer)=>void}){
 const [custom,setCustom]=useState('');const values=answer?.status==='known'?answer.values:[];
 const set=(next:string[])=>onChange({status:'known',values:next});
 function add(){if(custom.trim()&&(step.kind!=='multi'||values.length<step.max)){set(step.kind==='items'||step.kind==='multi'?[...values,custom.trim()]:[custom.trim()]);setCustom('');}}
 if(step.kind==='scale')return <div className="scale-row">{[1,2,3,4,5].map(n=><button key={n} aria-pressed={values.includes(String(n))} onClick={()=>set([String(n)])}>{n}</button>)}<p>آرام و کم ← → زیاد و مشتاق</p></div>;
 if(step.kind==='wheel')return <div className="wheel-fields">{step.options.map(option=><label key={option}><span>{option}</span><select aria-label={option} value={answer?.numbers?.[option]??''} onChange={e=>{const numbers={...answer?.numbers};if(e.target.value)numbers[option]=Number(e.target.value);else delete numbers[option];onChange({status:'known',values:[],numbers});}}><option value="">نامشخص</option>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label>)}</div>;
 if(step.kind==='rank'){const order=values.length?values:step.options;return <div className="rank-list">{order.map((value,index)=><div key={value}><b>{index+1}</b><span>{value}</span><button aria-label={`بالا ${value}`} disabled={!index} onClick={()=>{const next=[...order];[next[index-1],next[index]]=[next[index],next[index-1]];set(next);}}>↑</button><button aria-label={`پایین ${value}`} disabled={index===order.length-1} onClick={()=>{const next=[...order];[next[index+1],next[index]]=[next[index],next[index+1]];set(next);}}>↓</button></div>)}<button className="small-link" onClick={()=>set([...order])}>این ترتیب را تأیید می‌کنم</button></div>;}
 return <><div className="choice-grid">{step.options.map((option,index)=><button key={option} className={values.includes(option)?'selected':''} aria-pressed={values.includes(option)} onClick={()=>set(step.kind==='multi'?(values.includes(option)?values.filter(v=>v!==option):values.length<step.max?[...values,option]:values):[option])}><span className="choice-symbol">{['✧','↗','◈','⌁','✺','◇'][index%6]}</span><strong>{option}</strong><span className="choice-tick">{values.includes(option)?'✓':'+'}</span></button>)}</div>
 {step.kind==='items'&&<ul className="item-list">{values.map((value,i)=><li key={`${value}-${i}`}><span>{value}</span><button aria-label={`حذف ${value}`} onClick={()=>set(values.filter((_,n)=>n!==i))}>×</button></li>)}</ul>}
 <details open={step.kind==='items'} className="custom-answer"><summary>{step.kind==='items'?'یک کارت کوتاه اضافه کن':'پاسخ خودم را دارم'}</summary><div><input aria-label="پاسخ کوتاه" maxLength={180} value={custom} onChange={e=>setCustom(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();add();}}} placeholder="چند کلمه کافی است…"/><button onClick={add} disabled={!custom.trim()}>افزودن</button></div></details>
 {values.filter(v=>!step.options.includes(v)).map((v,i)=>step.kind!=='items'&&<p className="own-answer" key={i}>{v}</p>)}</>;
}
