import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const root=path.resolve('../ai-studio-for-making-digital-product');
const release=path.join(root,'releases/career-compass-0.2.0');
fs.mkdirSync(release,{recursive:true});
fs.cpSync('packages/studio-kit',path.join(release,'studio-kit'),{recursive:true});
fs.copyFileSync('src/app/globals.css',path.join(release,'studio-kit/styles.css'));
for(const [source,target] of [['studio','reference'],['scripts/build-pwa.mjs','pwa/build-pwa.mjs'],['src/features/journey/pwa-status.tsx','pwa/pwa-status.tsx'],['src/app/manifest.ts','pwa/manifest.ts'],['tests/browser/pwa.spec.ts','pwa/pwa.spec.ts'],['docs/phase-2.md','phase-2.md']]){fs.mkdirSync(path.dirname(path.join(release,target)),{recursive:true});fs.cpSync(source,path.join(release,target),{recursive:true});}
const integration='# Career Compass 0.2.0 — 2026-09-12\n\nنسخه مرجع در releases/career-compass-0.2.0 است. موتورهای مشترک در studio-kit، metadata در reference و الگوی PWA در pwa قرار دارند.\n\nاین الگوی PWA مختص shell تک‌صفحه‌ای Next است؛ قبل از reuse نام cache، scope، مسیرها، متن فارسی و build hook را تغییر بده. قالب worker در reference/pwa-worker.template.js است. PWA هنوز package عمومی نیست. به sharp (نسخه lockfile پروژه مرجع) برای تولید آیکون با کد نیاز دارد.\n\nRemember و خروجی‌های آن حفظ شده‌اند. source اصلی Studio Kit فعلاً پروژه Career Compass است؛ snapshotها را مستقیم ویرایش نکن. snapshot 0.1.0 حفظ می‌شود.\n\nکاتالوگ ۵۸ asset فقط metadata و checksum است؛ بازبینی مجوز و preview باقی مانده است. آیکون‌های این فاز با کد اختصاصی ساخته شدند.\n\nاولویت بعدی: بازبینی محتوای کتاب، فونت محلی، آزمون ارتقای worker، smoke مصرف در پروژه دوم و جداکردن CSS ویژگی از CSS عمومی. AI و مراحل ۲–۹ هنوز ساخته نشده‌اند.\n';
fs.mkdirSync(path.join(root,'projects'),{recursive:true});fs.writeFileSync(path.join(root,'projects/career-compass-phase-2.md'),integration);
for(const file of ['README.md','backlog.md','component-library.md']){const target=path.join(root,file);const previous=fs.existsSync(target)?fs.readFileSync(target,'utf8'):'';const marker='## Career Compass integration 2026-09-12';if(!previous.includes(marker))fs.writeFileSync(target,previous+'\n\n'+marker+'\n\nبه `projects/career-compass-phase-2.md` مراجعه کن. بسته‌های واقعی: AppShell، ActionButton، ProgressMeter، content، engine، storage و session. ProgressPath و editor هنوز feature محلی‌اند. PWA الگوی پروژه است، نه موتور عمومی.\n');}
const entries=[];function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,e.name);if(e.isDirectory())walk(file);else entries.push({file:path.relative(release,file),sha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')});}}walk(release);fs.writeFileSync(path.join(root,'career-compass-0.2.0-manifest.json'),JSON.stringify(entries,null,2));console.log(`${entries.length} exported files`);
