'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {guidedCourse as course} from '@/content/guided-course';
import {changeGuided,completeGuided,freshGuided,keyFor,stageFacts,validAnswer,restoreGuided,type GuidedState,type GuidedAnswer} from '@compass/studio-kit/guided';
import {Sketch} from '@compass/studio-kit/sketch';
import {guidedInsights} from '@compass/studio-kit/guided-rules';
import {VisualMap} from '@compass/studio-kit/visual-map';
import {Interaction} from './interactions';
import {guidedRepository} from './persistence';
import './guided.css';

const describe=(a?:GuidedAnswer)=>!a?'هنوز ثبت نشده':a.status==='unknown'?'هنوز نمی‌دانم':a.numbers?Object.entries(a.numbers).map(([k,v])=>`${k}: ${v}`).join(' · '):a.values.join('، ');
export function GuidedApp(){
 const [state,setState]=useState<GuidedState>(freshGuided);const [ready,setReady]=useState(false);const [status,setStatus]=useState('در حال بازیابی…');const [view,setView]=useState<'work'|'report'|'atlas'>('work');const [sidebar,setSidebar]=useState(false);
 const repo=useRef<ReturnType<typeof guidedRepository>|null>(null);const current=useRef(state);const savedRevision=useRef(0);const pending=useRef<Promise<boolean>|null>(null);const conflict=useRef(false);const [busy,setBusy]=useState(false);
 useEffect(()=>{repo.current=guidedRepository();void repo.current.load().then(s=>{const normalized=restoreGuided(course,s);current.current=normalized;savedRevision.current=s.revision;setState(normalized);setReady(true);setStatus('روی این دستگاه ذخیره می‌شود');}).catch(()=>setStatus('بازیابی انجام نشد؛ داده قبلی پاک نشده است. صفحه را دوباره باز کن.'));},[]);
 function update(next:GuidedState){if(conflict.current)return;current.current=next;setState(next);setStatus('در حال ذخیره…');}
 const flush=useCallback(async function persist():Promise<boolean>{if(pending.current){const ok=await pending.current;return ok&&current.current.revision!==savedRevision.current?persist():ok;}if(!repo.current||conflict.current)return false;const snapshot=current.current;if(snapshot.revision===savedRevision.current)return true;pending.current=repo.current.save(snapshot,savedRevision.current).then(()=>{savedRevision.current=snapshot.revision;setStatus('ذخیره شد');return true;}).catch((e:Error)=>{conflict.current=e.message==='conflict';setStatus(conflict.current?'این مسیر در تب دیگری تغییر کرده؛ خروجی بگیر و صفحه را تازه کن.':'ذخیره نشد؛ دوباره تلاش کن یا پشتیبان بگیر.');return false;});const ok=await pending.current;pending.current=null;return ok&&current.current.revision!==savedRevision.current?persist():ok;},[]);
 useEffect(()=>{if(!ready)return;const timer=setTimeout(()=>void flush(),350);const warn=(e:BeforeUnloadEvent)=>{if(current.current.revision!==savedRevision.current){e.preventDefault();}};window.addEventListener('beforeunload',warn);return ()=>{clearTimeout(timer);window.removeEventListener('beforeunload',warn);};},[state,ready,flush]);
 const heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{if(ready&&view==='work')heading.current?.focus({preventScroll:true});},[state.stage,state.step,ready,view]);
 const stage=course[state.stage];const step=stage.steps[state.step];const answer=state.answers[keyFor(stage,step)];const facts=stageFacts(stage,state);const filled=facts.filter(f=>validAnswer(f.answer)).length;
 function commit(next:GuidedState){update({...next,revision:current.current.revision+1});}
 function respond(a:GuidedAnswer){commit(changeGuided(current.current,course,a));}
 async function next(){setBusy(true);try{if(!await flush())return;if(state.step===stage.steps.length-1){commit(completeGuided(current.current,stage));if(await flush())setView('report');}else commit({...current.current,step:state.step+1});}finally{setBusy(false);}}
 function navigate(index:number){commit({...current.current,stage:index,step:0});setView('work');setSidebar(false);}
 async function importBackup(file?:File){if(!file)return;try{if(file.size>2000000)throw Error();const imported=restoreGuided(course,JSON.parse(await file.text()));if(imported.step>=course[imported.stage].steps.length)throw Error();if(!window.confirm("پاسخ‌های این نسخه با پشتیبان جایگزین شوند؟"))return;commit({...imported,step:Math.min(imported.step,course[imported.stage].steps.length-1)});await flush();setView("work");}catch{setStatus("فایل پشتیبان معتبر نیست؛ پاسخ‌ها تغییر نکردند.");}}
 function download(){const blob=new Blob([JSON.stringify(current.current,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='career-compass-guided-v2.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const report=(index:number)=>{const s=course[index];return <section className="report-sheet" key={s.id}><span className="eyebrow">دفتر مسیر / {s.symbol}</span><h2>{s.title}</h2><p>{state.completed.includes(s.id)?state.stale.includes(s.id)?'نیازمند مرور پس از ویرایش':'مرور شده':'پیش‌نویس'}</p><VisualMap kind={s.map} color={s.color} items={s.map==='wheel'?s.steps[0].options.map(label=>({label,value:'',score:state.answers[keyFor(s,s.steps[0])]?.numbers?.[label]})):stageFacts(s,state).map(f=>({label:f.title,value:describe(f.answer)}))}/><div className="rule-notes"><h3>جمع‌بندی قاعده‌محور</h3>{guidedInsights(s,state).map(insight=><p key={insight.id}>{insight.text}<small> بر اساس: {insight.evidence.map(id=>s.steps.find(step=>step.id===id)?.title).join("، ")}</small></p>)}</div><div className="report-facts">{stageFacts(s,state).map(f=><article key={f.id}><h3>{f.title}</h3><p>{describe(f.answer)}</p></article>)}</div><p className="report-note">منشأ: پاسخ‌های خودت · عنوان‌های بلند در نقشه کوتاه شده‌اند؛ متن کامل در کارت‌هاست. چرخ، مقدارهای فعلی ثبت‌شده را نشان می‌دهد.</p></section>;};
 return <div className="guided" style={{'--accent-color':stage.color} as React.CSSProperties}><header className="guided-header"><div className="logo"><span>✧</span><div>قطب‌نما<small>دفتر اکتشاف مسیر من</small></div></div><span className="edition">یک قدم کوچک، یک نگاه تازه</span><button className="mobile-menu" onClick={()=>setSidebar(!sidebar)}>مرحله‌ها ☰</button><button className="atlas-button" onClick={()=>setView('atlas')}>اطلس من ↗</button></header>
 <div className="guided-layout"><aside className={`journey-sidebar ${sidebar?'open':''}`}><span className="eyebrow">۹ فصل برای کشف مسیر</span><nav>{course.map((s,i)=><button key={s.id} className={state.stage===i?'active':''} onClick={()=>navigate(i)} disabled={!ready}><span className="nav-number">{state.completed.includes(s.id)?'✓':s.symbol}</span><div>{s.title}<small>{state.stale.includes(s.id)?'نیازمند مرور':state.completed.includes(s.id)?'مرور شده':s.caption}</small></div></button>)}</nav><div className="sidebar-note">با سرعت خودت پیش برو.<br/>اینجا پاسخ درست و غلط نداریم.</div><a className="small-link" href="/legacy">یادداشت‌های نسخه قبلی ↗</a></aside>
 <main className="guided-main"><div className="workspace-heading"><span>فصل {stage.symbol} <b> / {stage.title}</b></span><span className="save-indicator" role="status">{status}</span></div>
 {!ready?<p className="loading-card">{status}</p>:view==='work'?<><div className="step-progress"><div style={{width:`${(state.step+1)/stage.steps.length*100}%`}}/></div><div className="work-grid"><section className="question-sheet"><div className="step-kicker"><span>قدم {state.step+1} از {stage.steps.length}</span><span>{step.kind==='reflection'?'بازتاب من':step.kind==='review'?'دیدن تصویر کامل':'کشف و تجربه'}</span></div><div className="guide-line"><span className="guide-avatar">✧</span><span>کمی مکث کنیم و با هم نگاه کنیم…</span></div><h1 ref={heading} tabIndex={-1} key={step.id}>{step.title}</h1><p className="step-hint">{step.hint}</p>
 {step.kind==='review'?<div className="review-list">{facts.filter(f=>f.id!=='reflection').map(f=><button key={f.id} onClick={()=>commit({...state,step:stage.steps.findIndex(s=>s.id===f.id)})}><span>{f.title}<b>{describe(f.answer)}</b></span><small>ویرایش ↗</small></button>)}<button className="confirm-review" onClick={()=>respond({status:'known',values:['نقشه را مرور کردم']})}>{validAnswer(answer)?'✓ مرور شد':'این نقشه را مرور کردم'}</button></div>:<Interaction key={`${stage.id}/${step.id}`} step={step} answer={answer} onChange={respond}/>}
 <div className="step-controls"><button className="next-step" disabled={!validAnswer(answer)||busy||conflict.current} onClick={()=>void next()}>{state.step===stage.steps.length-1?'دیدن گزارش این فصل':'ادامه مسیر'} <span>←</span></button><button className="unknown-answer" onClick={()=>respond({status:'unknown',values:[]})}>{answer?.status==='unknown'?'✓ برای مرور بعدی نگه داشتم':'هنوز نمی‌دانم'}</button><button className="previous-step" disabled={!state.step} onClick={()=>commit({...state,step:state.step-1})}>قدم قبل</button></div></section>
 <aside className="live-map"><div className="map-heading"><span>نقشه در حال شکل‌گیری</span><span>✎</span></div><Sketch kind={stage.map} color={stage.color} count={filled}/><div className="map-caption">{stage.caption}</div><div className="map-notes">{facts.filter(f=>validAnswer(f.answer)).slice(-3).map(f=><div key={f.id}><small>{f.title}</small><p>{describe(f.answer)}</p></div>)}</div><div className="guide-tip"><b>یادداشت راهنما</b><p>{guidedInsights(stage,state)[0].text}</p></div></aside></div></>:<><div className="report-toolbar"><h1>{view==='atlas'?'اطلس مسیر من':'نقشه این فصل'}</h1><button onClick={()=>setView('work')}>بازگشت به فعالیت</button><button onClick={()=>window.print()}>چاپ / ذخیره PDF</button><button onClick={download}>پشتیبان JSON</button></div>{view==='atlas'?course.map((_,i)=>report(i)):report(state.stage)}{view==='report'&&state.stage<8&&<button className="next-step" onClick={()=>navigate(state.stage+1)}>فصل بعدی ←</button>}</>}
 <footer className="guided-footer"><span>نسخه کارگاهی برای بازبینی · AI هنوز فعال نیست · انتخاب مرحله‌ها برای بررسی آزاد است</span><button onClick={download}>پشتیبان</button><label>بازیابی JSON<input aria-label="بازیابی JSON" type="file" accept=".json" disabled={!ready} onChange={e=>{void importBackup(e.target.files?.[0]);e.target.value="";}}/></label><button onClick={()=>void flush()}>تلاش دوباره برای ذخیره</button></footer></main></div></div>;
}
